version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    env_file:
      - ./.env.docker
    volumes:
      - .:/usr/src/app
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: patata
      POSTGRES_DB: userdb
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432

  adminer:
    image: adminer
    ports:
    
      - 127.0.0.1:8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  nginx:
    image: nginx:alpine
    ports:
      - 127.0.0.1:8084:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wannapop/static:/static
    depends_on:
      - flask

volumes:
  postgres_volume:
